src/app/routes/main.py
import flask
import flask_login
from nssl import NSSL

from ..injector import nssl_inject

bp = flask.Blueprint('main', __name__)


@bp.route('/', methods=['GET'])
def index():
    from ..models.user import User
    user: User = flask_login.current_user

    if not user.is_anonymous:
        return flask.redirect(flask.url_for('ShoppingList.index'))

    return flask.render_template('main/index.html')


@bp.route('/login', methods=['GET', 'POST'])
@nssl_inject
def login(nssl: NSSL):
    from ..models.user import User
    from ..forms.user import LoginForm
    from ..context import UserStorage

    form = LoginForm()
    if form.validate_on_submit():
        response = nssl.login(form.username.data, form.password.data)
        if response.success:
            user = User(user_data=response.data)
            UserStorage.add(user.user_id, user)

            flask_login.login_user(user)

            return flask.redirect(flask.url_for('ShoppingList.index'))

        flask.flash(response.error)

    return flask.render_template('main/login.html', title='Login', form=form)


@bp.route('/logout', methods=['GET'])
def logout():
    flask_login.logout_user()
    return flask.redirect(flask.url_for('main.index'))

src/app/templates/basic.layout.html
<!doctype html>
<html lang="en">
<head>
    <title>{% if title %}{{ title }} - NSSL{% else %}NSSL WebAPP{% endif %}</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet"
          href="{{ url_for('static', filename='node_modules/@fortawesome/fontawesome-free/css/all.min.css') }}">

    <link rel="stylesheet" href="/static/main.css">

</head>
<body>
{% block navbar %}
    <nav class="navbar navbar-dark bg-primary">
        <a class="navbar-brand">NSSL</a>

        <ul class="navbar-nav mr-auto">
            {% if current_user.is_anonymous %}
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('main.login') }}">Login</a>
                </li>
            {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('main.logout') }}">Logout</a>
                </li>
            {% endif %}

        </ul>
    </nav>
{% endblock %}
{% block container %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-auto">
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-danger mt-3" role="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>
        </div>


        {% block app_content %}
        {% endblock %}
    </div>
{% endblock %}
{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>

    {% block user_scripts %}
    {% endblock %}
{% endblock %}
</body>
</html>

src/app/templates/form.html
{% macro show_form(form,method='POST',class='') %}
    <form class="{{ class }}" method="{{ method }}">
        {% for field in form %}
            {{ show_field(field) }}
        {% endfor %}
    </form>
{% endmacro %}

{% macro show_field(field) %}
    {% if field.type == 'StringField' %}
        {{ print_input(field) }}
    {% elif field.type == 'PasswordField' %}
        {{ print_input(field,type='password') }}
    {% elif field.type == 'IntegerField' %}
        {{ print_integer_field(field) }}
    {% elif field.type == 'SubmitField' %}
        {{ print_submit(field) }}
    {% elif field.type == 'CSRFTokenField' %}
        {{ print_token(field) }}
    {% else %}
        <span>No Element for {{ field.type }}</span> <br/>
    {% endif %}
{% endmacro %}

{% macro print_input(field,type='text') %}
    <div class="form-group">
        <label for="{{ field.id }}">{{ field.label.text }}</label>
        <input type="{{ type }}" class="form-control" name="{{ field.name }}" id="{{ field.id }}"
               value="{{ field.data if field.data else '' }}">
        {{ print_errors(field) }}
    </div>
{% endmacro %}

{% macro print_integer_field(field) %}
    <div class="form-group">
        <label for="{{ field.id }}">{{ field.label.text }}</label>
        <input type="number" class="form-control" name="{{ field.name }}" id="{{ field.id }}"
               value="{{ field.data if field.data else '' }}">
        {{ print_errors(field) }}
    </div>
{% endmacro %}

{% macro print_submit(field) %}
    <button type="submit" name="{{ field.name }}" id="{{ field.id }}" class=" btn btn-primary">
        {{ field.label.text }}</button>
{% endmacro %}

{% macro print_token(field) %}
    {{ field }}
{% endmacro %}

{% macro print_errors(field) %}
    {% for error in field.errors %}
        <small class="form-text text-danger">
            {{ error }}
        </small>
    {% endfor %}
{% endmacro %}