src/app/forms/shopping_list.py
from flask_wtf import FlaskForm
from wtforms import IntegerField, StringField, SubmitField
from wtforms.validators import DataRequired, NumberRange


class NewShoppingListForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])

    submit = SubmitField('Create')


class EditShoppingListForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])

    submit = SubmitField('Edit')


class AddProductForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    gtin = StringField('GTin')
    amount = IntegerField('Amount', default='1', validators=[NumberRange(min=1)])

    submit = SubmitField('Add')


class EditProductForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    amount = IntegerField('Amount', default='1', validators=[NumberRange(min=1)])

    submit = SubmitField('Edit')

src/app/routes/shopping_list.py
import flask
import flask_login
from nssl import NSSL

from ..injector import nssl_inject

bp = flask.Blueprint("ShoppingList", __name__, url_prefix='/shoppingList')


@bp.route('/', methods=['GET', 'POST'])
@flask_login.login_required
@nssl_inject
def index(nssl: NSSL):
    from ..forms.shopping_list import NewShoppingListForm
    force = flask.request.args.get('refresh', False) == '1'

    form = NewShoppingListForm()
    if form.validate_on_submit():
        result = nssl.add_list(form.name.data)
        if not result.success:
            flask.flash(result.error)
        return flask.redirect(flask.url_for('ShoppingList.index', refresh=1))

    response = nssl.get_shopping_lists(force=force)
    if not response.success:
        flask.flash(response.error)
    lists = response.data.lists

    return flask.render_template('shopping_list/index.html',
                                 title='Shopping Lists',
                                 form=form,
                                 shopping_lists=lists)


@bp.route('/<int:item_id>', methods=['GET', 'POST'])
@flask_login.login_required
@nssl_inject
def show(nssl: NSSL, item_id: int):
    from ..forms.shopping_list import AddProductForm
    response = nssl.get_list(item_id)
    if not response.success:
        flask.flash(response.error)

    shopping_list = response.data

    if shopping_list is None:
        return flask.redirect(flask.url_for('ShoppingList.index'))

    form = AddProductForm()
    if form.validate_on_submit():
        response = nssl.add_product_to_list(item_id,
                                            form.name.data, form.amount.data,
                                            gtin=form.gtin.data)

        if not response.success:
            flask.flash(response.error)

        return flask.redirect(
            flask.url_for('ShoppingList.show', item_id=shopping_list.id))

    return flask.render_template('shopping_list/show.html',
                                 form=form,
                                 shopping_list=shopping_list)


@bp.route('/edit/<int:item_id>', methods=['GET', 'POST'])
@nssl_inject
def edit(nssl: NSSL, item_id: int):
    from ..forms.shopping_list import EditShoppingListForm

    response = nssl.get_list(item_id)
    if not response.success:
        flask.flash(response.error)
        return flask.redirect(flask.url_for('ShoppingList.index'))

    shopping_list = response.data
    form = EditShoppingListForm()
    if form.validate_on_submit():
        response = nssl.rename_list(item_id, form.name.data)

        if not response.success:
            flask.flash(response.error)
        else:
            shopping_list = response.data

    form.name.data = shopping_list.name

    return flask.render_template('shopping_list/edit.html',
                                 form=form,
                                 shopping_list=shopping_list)


@bp.route('/<int:list_id>/changeAmount/<int:item_id>/<int:amount>',
          methods=['GET'])
@nssl_inject
def change_amount(nssl: NSSL, list_id: int, item_id: int, amount: int):
    if amount <= 0:
        flask.flash('Value must be greater than 0')
        return flask.redirect(flask.url_for('ShoppingList.show', item_id=list_id))

    list_response = nssl.get_list(list_id)
    if not list_response.success:
        flask.flash(list_response.error)
        return flask.redirect(flask.url_for('ShoppingList.index'))

    response = nssl.change_list_product(list_id, item_id, new_amount=amount)
    if not response.success:
        flask.flash(response.error)

    return flask.redirect(flask.url_for('ShoppingList.show', item_id=list_id))


@bp.route('/delete/<int:item_id>')
@nssl_inject
def delete(nssl: NSSL, item_id: int):
    response = nssl.delete_list(item_id)
    if not response.success:
        flask.flash(response.error)

    return flask.redirect(flask.url_for('ShoppingList.index', refresh=1))


@bp.route('/<int:list_id>/delete/<int:item_id>')
@nssl_inject
def delete_product(nssl: NSSL, list_id: int, item_id: int):
    response = nssl.delete_product_from_list(list_id, item_id)
    if not response.success:
        flask.flash(response.error)

    return flask.redirect(flask.url_for('ShoppingList.show', item_id=list_id))


@bp.route('/<int:list_id>/changeAmount/<int:item_id>/edit',
          methods=['GET', 'POST'])
@nssl_inject
def edit_product(nssl: NSSL, list_id: int, item_id: int):
    from ..forms.shopping_list import EditProductForm

    list_response = nssl.get_list(list_id)
    if not list_response.success:
        flask.flash(list_response.error)
        return flask.redirect(flask.url_for('ShoppingList.index'))
    shopping_List = list_response.data

    item = shopping_List.get_product(item_id)
    if item is None:
        flask.flash('No item found')
        return flask.redirect(flask.url_for('ShoppingList.show', item_id=list_id))

    form = EditProductForm()
    if form.validate_on_submit():
        response = nssl.change_list_product(list_id, item_id,
                                            new_amount=form.amount.data,
                                            new_name=form.name.data)
        if not response.success:
            flask.flash(response.error)
        else:
            return flask.redirect(flask.url_for('ShoppingList.show', item_id=list_id))

    if flask.request.method == 'GET':
        form.name.data = item.name
        form.amount.data = item.amount

    return flask.render_template('shopping_list/product.edit.html',
                                 shopping_list=shopping_List,
                                 product=item,
                                 form=form)

src/app/templates/shopping_list/basic.layout.html
{% extends 'basic.layout.html' %}

{% block app_content %}
    <div class="row mt-3">
        <div class="col">
            {% block bread_crump %}
            {% endblock %}
        </div>
    </div>
    <div class="row justify-content-center">
        {% block content_col %}
            <div class="col">
                {% block content %}
                {% endblock %}
            </div>
        {% endblock %}
    </div>
{% endblock %}

src/app/templates/shopping_list/edit.html
{% extends 'shopping_list/basic.layout.html' %}
{% from 'form.html' import show_form %}

{% block bread_crump %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ url_for('ShoppingList.index') }}">{{ current_user.username }}</a></li>
            <li class="breadcrumb-item"><a href="{{ url_for('ShoppingList.index') }}">ShoppingLists</a></li>
            <li class="breadcrumb-item active" aria-current="page">
                <a href="{{ url_for('ShoppingList.show',item_id=shopping_list.id) }}">{{ shopping_list.name }}</a></li>
        </ol>
    </nav>
{% endblock %}

{% block content_col %}
    <div class="col-auto">
        <div class="card">
            <div class="card-header">
                <i class="fas fa-edit ml-1"></i>
                {{ shopping_list.name }}
            </div>
            <div class="card-body">
                {{ show_form(form) }}
            </div>
        </div>
    </div>
{% endblock %}

src/app/templates/shopping_list/index.html
{% extends 'shopping_list/basic.layout.html' %}
{% from 'form.html' import show_form %}

{% block bread_crump %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a
                    href="{{ url_for('ShoppingList.index') }}">{{ current_user.username }}</a></li>
            <li class="breadcrumb-item active" aria-current="page"><a>ShoppingLists</a></li>
        </ol>
    </nav>
{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-header"><span class="mr-1">Shopping Lists</span>
             <a href="?refresh=1"><i class="fas fa-sync"></i></a>
        </div>
        <div class="card-bod">
            <div class="mt-3 ml-3">
                {{ show_form(form,class='form-inline form-inline-elements') }}
            </div>
            <hr/>

            <div class="m-3">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">#</th>

                        <th scope="col">Name</th>
                        <th>Refresh TimeStamp</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for shopping_list in shopping_lists %}
                        <tr>
                            <th scope="row">{{ loop.index }}</th>

                            <td>
                                <a href="{{ url_for('ShoppingList.show',item_id=shopping_list.id) }}">
                                    {{ shopping_list.name }}</a>
                            </td>
                            <td>{{ shopping_list.refresh_data | df }}</td>
                            <td>
                                <a href="{{ url_for('ShoppingList.edit',item_id=shopping_list.id) }}">
                                    <i class="fas fa-edit"></i></a>
                                <a href="{{ url_for('ShoppingList.delete',item_id=shopping_list.id) }}">
                                    <i class="fas fa-trash"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

src/app/templates/shopping_list/product.edit.html
{% extends 'shopping_list/basic.layout.html' %}
{% from 'form.html' import show_form %}

{% block bread_crump %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ url_for('ShoppingList.index') }}">{{ current_user.username }}</a></li>
            <li class="breadcrumb-item"><a href="{{ url_for('ShoppingList.index') }}">ShoppingLists</a></li>
            <li class="breadcrumb-item active" aria-current="page">
                <a href="{{ url_for('ShoppingList.show',item_id=shopping_list.id) }}">{{ shopping_list.name }}</a></li>
        </ol>
    </nav>
{% endblock %}

{% block content_col %}
    <div class="col-auto">
        <div class="card">
            <div class="card-header">
                <i class="fas fa-edit ml-1"></i>
                {{ shopping_list.name }} - {{ product.name }}
            </div>
            <div class="card-body">
                {{ show_form(form) }}
            </div>
        </div>
    </div>
{% endblock %}

src/app/templates/shopping_list/show.html
{% extends 'shopping_list/basic.layout.html' %}
{% from 'form.html' import show_form %}

{% block bread_crump %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a
                    href="{{ url_for('ShoppingList.index') }}">{{ current_user.username }}</a></li>
            <li class="breadcrumb-item"><a href="{{ url_for('ShoppingList.index') }}">ShoppingLists</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ shopping_list.name }}</li>
        </ol>
    </nav>
{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-header"><span class="mr-1">{{ shopping_list.name }}</span>
            <a href="?refresh=1"><i class="fas fa-sync"></i></a>
            <a href="{{ url_for('ShoppingList.edit',item_id=shopping_list.id) }}"><i class="fas fa-edit"></i></a>
        </div>
        <div class="card-body">
            <div class="mt-3 ml-3">
                {{ show_form(form,class='form-inline form-inline-elements') }}
            </div>
            <hr/>

            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Name</th>
                    <th scope="col">GTin</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                {% for product in shopping_list.products %}
                    <tr>
                        <th scope="row">{{ loop.index }}</th>
                        <td>
                            {% set amount = product.amount or 0 %}
                            {{ amount }}
                            {% if amount > 1 %}
                                <a href="{{ url_for('ShoppingList.change_amount',
                                list_id=shopping_list.id,item_id=product.id,amount=amount - 1) }}">
                                    <i class="fas fa-minus"></i></a>
                            {% endif %}
                            <a href="{{ url_for('ShoppingList.change_amount',
                                    list_id=shopping_list.id,item_id=product.id,amount=amount + 1) }}">
                                <i class="fas fa-plus"></i></a>
                        </td>
                        <td>{{ product.name or 'No Name' }}</td>
                        <td>{{ product.gtin or '' }}</td>
                        <td>
                            <a href="{{ url_for('ShoppingList.delete_product',
                                list_id=shopping_list.id,item_id=product.id) }}">
                                <i class="fas fa-trash"></i></a>

                            <a href="{{ url_for('ShoppingList.edit_product',
                                list_id=shopping_list.id,item_id=product.id) }}">
                                <i class="fas fa-edit"></i></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="card-footer text-muted">
            Refresh TimeStamp: {{ shopping_list.refresh_data | df }}
        </div>
    </div>
{% endblock %}